// ─── Backend Seed Data Definition ─────────────────────────────
// Contains production seed records for initializing PostgreSQL database

export const seedUsers = [
  {
    id: 'usr-001',
    customerId: 'HZ-20241001',
    firstName: 'Adebayo',
    lastName: 'Okonkwo',
    email: 'adebayo@mailinator.com',
    phone: '+2348012345678',
    role: 'customer',
    isVerified: true,
  },
  {
    id: 'usr-002',
    customerId: 'HZ-20241002',
    firstName: 'Abdul',
    lastName: 'User',
    email: 'abdul@mailinator.com',
    phone: '+2348012345678',
    role: 'customer',
    isVerified: true,
  },
  {
    id: 'usr-superadmin',
    customerId: 'HZ-SADMIN-001',
    firstName: 'Super Admin',
    lastName: 'Hamza',
    email: 'superadmin@mailinator.com',
    phone: '+2348099999999',
    role: 'super_admin',
    isVerified: true,
    groupName: 'Super Admin',
  },
  {
    id: 'usr-admin',
    customerId: 'HZ-ADMIN-001',
    firstName: 'Admin',
    lastName: 'Hamza',
    email: 'admin@mailinator.com',
    phone: '+2348099999991',
    role: 'admin',
    isVerified: true,
    groupName: 'Admin',
  },
  {
    id: 'usr-[#0A1128]-finance',
    customerId: 'HZ-FINANCE-001',
    firstName: 'Finance',
    lastName: 'Manager',
    email: 'finance@mailinator.com',
    phone: '+2348099999992',
    role: 'finance',
    isVerified: true,
    groupName: 'Finance Manager',
  },
  {
    id: 'usr-procurement-001',
    customerId: 'HZ-PROC-001',
    firstName: 'Procurement',
    lastName: 'Specialist',
    email: 'procurement@mailinator.com',
    phone: '+2348099999993',
    role: 'procurement',
    isVerified: true,
    groupName: 'Procurement Specialist',
  },
  {
    id: 'usr-wh-cn-001',
    customerId: 'HZ-WHCN-001',
    firstName: 'China Hub',
    lastName: 'Operator',
    email: 'warehouse_cn@mailinator.com',
    phone: '+862088889999',
    role: 'warehouse_cn',
    isVerified: true,
    groupName: 'Warehouse (China Hub)',
  },
  {
    id: 'usr-wh-ng-001',
    customerId: 'HZ-WHNG-001',
    firstName: 'Nigeria Hub',
    lastName: 'Operator',
    email: 'warehouse_ng@mailinator.com',
    phone: '+2348021234567',
    role: 'warehouse_ng',
    isVerified: true,
    groupName: 'Warehouse (Nigeria Hub)',
  },
  {
    id: 'usr-clearance-001',
    customerId: 'HZ-CLEAR-001',
    firstName: 'Customs',
    lastName: 'Clearance Agent',
    email: 'clearance@mailinator.com',
    phone: '+2348039876543',
    role: 'clearance_agent',
    isVerified: true,
    groupName: 'Clearance Agent',
  },
  {
    id: 'usr-ss-driver',
    customerId: 'DRV-SS01',
    firstName: 'Sani',
    lastName: 'Umar',
    email: 'ss@mailinator.com',
    phone: '+2348011223344',
    role: 'driver',
    isVerified: true,
    groupName: 'Logistics Driver',
  },
  {
    id: 'usr-drv-001',
    customerId: 'DRV-001',
    firstName: 'Chukwudi',
    lastName: 'Emmanuel',
    email: 'chukwudi.driver@mailinator.com',
    phone: '+2348055667788',
    role: 'driver',
    isVerified: true,
    groupName: 'Logistics Driver',
  },
  {
    id: 'usr-drv-002',
    customerId: 'DRV-002',
    firstName: 'Babatunde',
    lastName: 'Raji',
    email: 'babatunde.driver@mailinator.com',
    phone: '+2348033221100',
    role: 'driver',
    isVerified: true,
    groupName: 'Logistics Driver',
  },
  {
    id: 'usr-drv-003',
    customerId: 'DRV-003',
    firstName: 'Ibrahim',
    lastName: 'Musa',
    email: 'ibrahim.driver@mailinator.com',
    phone: '+2348123456789',
    role: 'driver',
    isVerified: true,
    groupName: 'Logistics Driver',
  },
];

export const seedWallet = {
  id: 'wal-001',
  customerId: 'usr-001',
  balance: 245000,
  currency: 'NGN',
  escrowHeld: 15000,
  availableBalance: 230000,
  lastTopUpAt: '2024-10-15T11:30:00Z',
};

export const seedTransactions = [
  {
    id: 'txn-001',
    customerId: 'usr-001',
    type: 'credit',
    category: 'top_up',
    amount: 100000,
    currency: 'NGN',
    balanceAfter: 245000,
    description: 'Wallet top-up via Paystack',
    referenceId: 'PAY-20241015-998',
  },
  {
    id: 'txn-002',
    customerId: 'usr-001',
    type: 'debit',
    category: 'shipping_payment',
    amount: 30000,
    currency: 'NGN',
    balanceAfter: 145000,
    description: 'Shipping fee for consolidation #CNS-20241016-001',
    referenceId: 'CNS-20241016-001',
  },
];

export const seedPackages = [
  {
    id: 'pkg-001',
    trackingId: 'HZ-AIR-20241001-001',
    chineseTrackingNo: 'SF1092839102',
    customerId: 'usr-001',
    customerName: 'Adebayo Okonkwo',
    description: 'Sample Textiles & Fabric Swatches',
    shippingMethod: 'air',
    weightKg: 12.5,
    volumeCbm: 0.08,
    declaredValueUsd: 450,
    status: 'arrived_ng',
    warehouseLocation: 'B-04-12',
    originHub: 'Guangzhou CAN',
    destinationHub: 'Lagos LOS',
    estimatedDeliveryDays: '3-5 Days',
    createdAt: '2026-08-20T09:00:00Z',
  },
  {
    id: 'pkg-002',
    trackingId: 'HZ-SEA-20241002-004',
    chineseTrackingNo: 'ZTO887629104',
    customerId: 'usr-002',
    customerName: 'Abdul User',
    description: 'Heavy Industrial Auto Spare Parts',
    shippingMethod: 'sea',
    weightKg: 350.0,
    volumeCbm: 2.4,
    declaredValueUsd: 3200,
    status: 'received_cn',
    warehouseLocation: 'A-01-05',
    originHub: 'Guangzhou CAN',
    destinationHub: 'Lagos LOS',
    estimatedDeliveryDays: '30-40 Days',
    createdAt: '2026-08-22T14:30:00Z',
  },
  {
    id: 'pkg-003',
    trackingId: 'HZ-AIR-20241017-004',
    chineseTrackingNo: 'YTO992830192',
    customerId: 'usr-001',
    customerName: 'Adebayo Okonkwo',
    description: 'Consumer Electronics & Smartwatches',
    shippingMethod: 'air',
    weightKg: 8.2,
    volumeCbm: 0.04,
    declaredValueUsd: 1200,
    status: 'received_cn',
    warehouseLocation: 'C-02-09',
    originHub: 'Guangzhou CAN',
    destinationHub: 'Lagos LOS',
    estimatedDeliveryDays: '3-5 Days',
    createdAt: '2026-08-25T10:15:00Z',
  },
];

export const seedConsolidations = [
  {
    id: 'cns-001',
    consolidationId: 'CNS-2026-0801',
    customerId: 'usr-001',
    customerName: 'Adebayo Okonkwo',
    packageIds: ['pkg-001', 'pkg-003'],
    shippingMethod: 'air',
    destinationWarehouse: 'lagos',
    paymentMethod: 'wallet',
    totalWeightKg: 20.7,
    totalCbm: 0.12,
    shippingFee: 45540,
    originCountry: 'Guangzhou Hub',
    status: 'ready_to_batch',
    createdAt: '2026-08-26T10:00:00Z',
  },
  {
    id: 'cns-002',
    consolidationId: 'CNS-2026-0802',
    customerId: 'usr-002',
    customerName: 'Abdul User',
    packageIds: ['pkg-002'],
    shippingMethod: 'sea',
    destinationWarehouse: 'lagos',
    paymentMethod: 'wallet',
    totalWeightKg: 350.0,
    totalCbm: 2.4,
    shippingFee: 504000,
    originCountry: 'Guangzhou Hub',
    status: 'packaging',
    createdAt: '2026-08-27T08:30:00Z',
  },
];
export const seedBatches = [
  {
    id: 'btc-001',
    masterTrackingId: 'MB-SEA-20240928',
    carrierName: 'COSCO Shipping Lines',
    shippingMethod: 'sea',
    shippingType: 'sea',
    flightVoyageNo: 'COS-VY-202409',
    containerNumber: 'COSU63920194',
    status: 'arrived_ng',
    totalPackagesCount: 48,
    totalWeightKg: 4200,
    totalCbm: 28.5,
    departureDate: '2026-08-01T00:00:00Z',
    estimatedArrivalDate: '2026-08-24T00:00:00Z',
  },
  {
    id: 'btc-002',
    masterTrackingId: 'MB-AIR-20241018',
    carrierName: 'Ethiopian Cargo FLT-802',
    shippingMethod: 'air',
    shippingType: 'air',
    flightVoyageNo: 'ET-FLT-802',
    containerNumber: 'ULD-ET-99201',
    status: 'shipping_exported',
    totalPackagesCount: 18,
    totalWeightKg: 410,
    totalCbm: 3.2,
    departureDate: '2026-08-24T00:00:00Z',
    estimatedArrivalDate: '2026-08-27T00:00:00Z',
  },
];

export const seedProcurements = [
  {
    id: 'pr-001',
    customerId: 'usr-001',
    customerName: 'Adebayo Okonkwo',
    supplierUrl: 'https://detail.1688.com/offer/674829102.html',
    specifications: 'High Grade Silk Swatches (Red & Navy Blue, 50 meters each)',
    quantity: 100,
    targetPriceRmb: 25.0,
    totalEstimatedNaira: 550000,
    status: 'submitted',
    submittedAt: '2026-08-23T11:00:00Z',
  },
];

export const seedExchangeRate = {
  id: 'rate-001',
  rateNairaPerRmb: 220.0,
  platformRate: 220.0,
  buyRate: 215.0,
  sellRate: 225.0,
  isActive: true,
};

export const seedExchanges = [
  {
    id: 'ex-001',
    customerId: 'usr-001',
    customerName: 'Adebayo Okonkwo',
    amountNaira: 1540000,
    amountRmb: 7000,
    exchangeRateUsed: 220.0,
    status: 'completed',
    createdAt: '2026-08-21T15:20:00Z',
  },
];

export const seedDeliveries = [];
export const seedNotifications = [];
